### ISSUE TITLE
Update to 1.18, using ProtocolLib - Should I MR?

### ISSUE THREAD

**Issue by justablob** [jmattingley23/AppleSkinSpigot#1]
Hey man, first off, I recently found your plugin and really like it, and am using it on a server with about 60 active players. 

Since your plugin uses NMS, it was not compatible with 1.18, so I made some changes to the source to use ProtocolLib instead of `CraftPlayer...sendPacket()` and to import PacketDataSerializer using reflection (new versions have it inside `net.minecraft.network`, old ones inside NMS). If you're interested in upstreaming these changes, I can open a MR. I'm not the greatest at Java, and even worse at Spigot plugin development, but the changes aren't too big and in my short tests, it seemed to work on all versions from 1.13.2 up to 1.18.

Also, I didn't bother to update the tests yet.

Since ProtocolLib would be added as a dependency, I wanted to ask first if you want a MR.

**Comment by kittenchilly** [comment]
I want to use this on my 1.18 version, and I'd love if you made it public if the maintainer doesn't respond.

**Comment by jmattingley23** [comment]
Thanks for the comments!  It makes me happy to see people are using + enjoying the plugin.  I think for now I would prefer to not add any additional dependencies, just to keep things simple for the end users.

I didn't realize spigot had a release build for 1.18 already, I'll update the plugin today and have a 1.18 compatible version out tonight.

**Comment by jmattingley23** [comment]
Just posted an updated `.jar` with 1.18 support.  Let me know if you have any issues.

**Comment by justablob** [comment]
The 1.18 jar works with 1.18, but not 1.17.1. Looking at the code you have going on (abstraction into 1.17.1 and 1.18 CraftPlayer classes), it makes me think that it was supposed to work between both versions?

Btw, it's not the API version in `plugin.yml`, I had to change it to 1.17 to make it load on the older server.

**Comment by jmattingley23** [comment]
Yeah, my intent was to make a universal jar that would work on both - I’ll take a look and see if I can figure out what’s wrong with it on 1.17.1 servers.  Glad to hear its working for you on 1.18 at least

**Comment by jmattingley23** [comment]
Just pushed a new `.jar` that should be compatible with both versions.  I ended up just refactoring everything to maven submodules to make the build process easier, since some of the fields were named differently in the 1.18 release.  I'll have support for 1.18.1 out soon as well.

**Comment by jmattingley23** [comment]
Ok, everything seems to be working for 1.18.1 as well
